In [4]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import matplotlib.pyplot as plt
import pandas as pd
from src.model import BasicModel

plt.rcParams['figure.figsize'] = 15.7,13.27
plt.rcParams['font.family'] = 'AppleGothic'

class LEARN_INFO:
    def __init__(self, name, columns, is_contain_cluster_label=False, matching_type="general", jump=3):
        self.name = name
        self.columns = columns
        self.is_label = is_contain_cluster_label
        self.matching = matching_type
        self.jump = jump
    

# INPUT_REPORT_SIMULATION = [
#     LEARN_INFO(name="univariate", columns=['energy (kw 15min)'], is_contain_cluster_label=False),
#     LEARN_INFO(name="with cluster label", columns=['energy (kw 15min)'], is_contain_cluster_label=True),
# ]

DEFAULT_COLUMNS = [
    'energy (kw 15min)',
    ['week sin',
    'week cos'],
    ['year sin',
    'year cos'],
    'season idx',
    'weather idx',
    'avg ta',
    'avg rhm'
]

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
cm = ClusterModel(name="cluster test",
                   columns=['energy (kw 15min)', 'week sin', 'week cos'],
                   is_switch=False)
cm

###### Basic Model Information ######
 - name : cluster test
 - columns : energy (kw 15min),week sin,week cos
 - datas : 
                     energy (kw 15min)  week sin  week cos
Date Time                                                 
2017-01-01 00:00:00              15250  0.707107 -0.707107
2017-01-01 01:00:00              14000  0.680173 -0.733052
2017-01-01 02:00:00              14750  0.652287 -0.757972
2017-01-01 03:00:00              29500  0.623490 -0.781831
2017-01-01 04:00:00              15750  0.593820 -0.804598
 - norm_datas : 
                     energy (kw 15min)  week sin  week cos  cluster energy
Date Time                                                                 
2017-01-01 00:00:00          -0.719354  0.999545 -0.995537       -0.488868
2017-01-01 01:00:00          -0.811090  0.961422 -1.032194       -0.581751
2017-01-01 02:00:00          -0.756048  0.921953 -1.067402       -0.644819
2017-01-01 03:00:00           0.326432  0.881193 -1.101113       -0.16206

In [43]:
cm.norm_datas['train']

energy (kw 15min)  week sin  week cos  cluster energy
Date Time                                                                 
2017-01-01 00:00:00          -0.719354  0.999545 -0.995537       -0.488868
2017-01-01 01:00:00          -0.811090  0.961422 -1.032194       -0.581751
2017-01-01 02:00:00          -0.756048  0.921953 -1.067402       -0.644819
2017-01-01 03:00:00           0.326432  0.881193 -1.101113       -0.162060
2017-01-01 04:00:00          -0.682660  0.839198 -1.133279       -0.420066
...                                ...       ...       ...             ...
2017-12-31 19:00:00          -1.196379  0.104470 -1.405405        0.803458
2017-12-31 20:00:00          -1.141338  0.051620 -1.408367        0.703695
2017-12-31 21:00:00          -1.214726 -0.001304 -1.409355        0.583292
2017-12-31 22:00:00          -1.196379 -0.054228 -1.408367       -0.079498
2017-12-31 23:00:00          -1.343156 -0.107078 -1.405405       -0.253796

[8760 rows x 4 columns]

In [44]:
cm.set_window()

###### [Notice] generate cluster window start ###### 

Total window size: 4
Input indices: [0 1 2]
Label indices: [3]
Label column name(s): ['energy (kw 15min)']

###### [Notice] generate cluster window success ###### 



In [45]:
for _ in cm.window.train.take(1):
    print(_)

(<tf.Tensor: shape=(32, 3, 3), dtype=float32, numpy=
array([[[-7.19353974e-01,  9.99545336e-01, -9.95537043e-01],
        [-8.11089575e-01,  9.61422503e-01, -1.03219390e+00],
        [-7.56048203e-01,  9.21953142e-01, -1.06740224e+00]],

       [[-8.11089575e-01,  9.61422503e-01, -1.03219390e+00],
        [-7.56048203e-01,  9.21953142e-01, -1.06740224e+00],
        [ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00]],

       [[-7.56048203e-01,  9.21953142e-01, -1.06740224e+00],
        [ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00],
        [-6.82659686e-01,  8.39197755e-01, -1.13327861e+00]],

       [[ 3.26432228e-01,  8.81192625e-01, -1.10111284e+00],
        [-6.82659686e-01,  8.39197755e-01, -1.13327861e+00],
        [-1.13898791e-01,  7.96027422e-01, -1.16385436e+00]],

       [[-6.82659686e-01,  8.39197755e-01, -1.13327861e+00],
        [-1.13898791e-01,  7.96027422e-01, -1.16385436e+00],
        [-7.72045404e-02,  7.51741946e-01, -1.19279742e+00]],

       [[-1.13898791e-

In [46]:
cm.norm_datas['test']

energy (kw 15min)  week sin  week cos  cluster energy
Date Time                                                                 
2018-04-02 00:00:00          -0.774395 -0.159780 -1.400472       -0.238993
2018-04-02 01:00:00          -0.829437 -0.212261 -1.393575       -0.333230
2018-04-02 02:00:00          -0.847784 -0.264446 -1.384724       -0.359083
2018-04-02 03:00:00          -0.847784 -0.316264 -1.373932        0.096259
2018-04-02 04:00:00          -0.829437 -0.367641 -1.361213       -0.056356
...                                ...       ...       ...             ...
2018-09-19 19:00:00          -0.187287 -0.709012  1.227085       -0.442108
2018-09-19 20:00:00          -0.425800 -0.662683  1.252644       -0.837591
2018-09-19 21:00:00          -0.352411 -0.615430  1.276455       -0.995580
2018-09-19 22:00:00          -0.444147 -0.567317  1.298487       -1.057757
2018-09-19 23:00:00          -0.499188 -0.518413  1.318707       -1.142357

[4104 rows x 4 columns]

In [47]:
for _ in cm.window.test.take(1):
    print(_)

(<tf.Tensor: shape=(32, 3, 3), dtype=float32, numpy=
array([[[-0.77439535, -0.15978044, -1.4004716 ],
        [-0.8294367 , -0.2122609 , -1.3935748 ],
        [-0.84778386, -0.26444632, -1.3847241 ]],

       [[-0.8294367 , -0.2122609 , -1.3935748 ],
        [-0.84778386, -0.26444632, -1.3847241 ],
        [-0.84778386, -0.3162637 , -1.3739319 ]],

       [[-0.84778386, -0.26444632, -1.3847241 ],
        [-0.84778386, -0.3162637 , -1.3739319 ],
        [-0.8294367 , -0.3676406 , -1.3612132 ]],

       [[-0.84778386, -0.3162637 , -1.3739319 ],
        [-0.8294367 , -0.3676406 , -1.3612132 ],
        [-0.77439535, -0.41850513, -1.3465858 ]],

       [[-0.8294367 , -0.3676406 , -1.3612132 ],
        [-0.77439535, -0.41850513, -1.3465858 ],
        [-0.7010068 , -0.46878618, -1.3300701 ]],

       [[-0.77439535, -0.41850513, -1.3465858 ],
        [-0.7010068 , -0.46878618, -1.3300701 ],
        [-0.5358827 , -0.5184134 , -1.3116894 ]],

       [[-0.7010068 , -0.46878618, -1.3300701 ],
    

In [51]:
_ = {
    "univariate": ['energy (kw 15min)'],
    "multivariate (week)": [
        'energy (kw 15min)',
        'week sin',
        'week cos'
    ],
    "multivariate (year)": [
        'energy (kw 15min)',
        'year sin',
        'year cos',
    ],
    "multivariate (weather)": [
        'energy (kw 15min)',
        'weather idx'
    ],
    "multivariate (avg ta)": [
        'energy (kw 15min)',
        'avg ta'
    ],
    "multivariate (avg rhm)": [
        'energy (kw 15min)',
        'avg rhm'
    ]
}

# Input Report Simulation
IRS = []
for key in _.keys():
    IRS.append(
        LEARN_INFO(name=key, 
                   columns=_[key], 
                   is_contain_cluster_label=False),
    )

# Training Model Array 
TMA = []

is_switch = False

for _ in IRS:
    cm = ClusterModel(name=_.name,
                   columns=_.columns,
                   is_switch=is_switch)
    
    cm.set_window()
    cm.set_model()
    print(cm)
    cm.training(epochs=50)
    
    cm.set_predict(is_reshape=True)
    cm.set_predict(is_reshape=True, is_val_datas=True)
    
    TMA.append(cm)
    
test_evaluate_df = pd.DataFrame();
val_evaluate_df = pd.DataFrame();

for _ in TMA:
    test_evaluate_df = test_evaluate_df.append(_.statistic(), ignore_index=True)
    val_evaluate_df = val_evaluate_df.append(_.statistic(is_val_datas=True), ignore_index=True)
    
test_evaluate_df.index = [_.name for _ in TMA]
val_evaluate_df.index = [_.name for _ in TMA]

###### [Notice] (multivariate (avg rhm)) set predict (validation) info start ###### 

0 / 91
50 / 91
91 / 91 complete.

###### [Notice] set predict info success ###### 



In [52]:
test_evaluate_df

ecv       mae  mean dis  mean sim       mse  \
univariate               72.372349  0.268569  1.477210  0.926195  0.112089   
multivariate (week)      66.861128  0.295644  1.609124  0.914677  0.134448   
multivariate (year)      41.324484  0.358794  2.013889  0.838926  0.238053   
multivariate (weather)   72.103086  0.270519  1.485291  0.926505  0.113181   
multivariate (avg ta)  -395.526448  1.212041  6.150250 -0.371676  2.010408   
multivariate (avg rhm) -269.922067  1.005096  5.091254 -0.099452  1.500816   

                                tss          wss  
univariate              1456.910039   402.510027  
multivariate (week)     1456.910039   482.803557  
multivariate (year)     1456.910039   854.849482  
multivariate (weather)  1456.910039   406.432942  
multivariate (avg ta)   1456.910039  7219.374564  
multivariate (avg rhm)  1456.910039  5389.431727

In [53]:
val_evaluate_df

ecv       mae  mean dis  mean sim       mse  \
univariate               63.356216  0.326233  1.761457  0.905411  0.159632   
multivariate (week)      57.374072  0.354586  1.893114  0.897221  0.185693   
multivariate (year)     -46.199919  0.724231  3.524072  0.535617  0.636895   
multivariate (weather)   63.153058  0.328524  1.768714  0.904099  0.160517   
multivariate (avg ta)  -278.215040  1.022290  5.291247 -0.005535  1.647630   
multivariate (avg rhm) -181.995619  0.880277  4.525433 -0.008199  1.228466   

                               tss          wss  
univariate              832.494756   305.057577  
multivariate (week)     832.494756   354.858614  
multivariate (year)     832.494756  1217.106656  
multivariate (weather)  832.494756   306.748864  
multivariate (avg ta)   832.494756  3148.620378  
multivariate (avg rhm)  832.494756  2347.598737

In [8]:
_ = {
    "univariate": ['energy (kw 15min)'],
    "multivariate (week)": [
        'energy (kw 15min)',
        'week sin',
        'week cos'
    ],
    "multivariate (weather)": [
        'energy (kw 15min)',
        'weather idx'
    ],
#     "multivariate (year)": [
#         'energy (kw 15min)',
#         'year sin',
#         'year cos',
#     ],

#     "multivariate (avg ta)": [
#         'energy (kw 15min)',
#         'avg ta'
#     ],
#     "multivariate (avg rhm)": [
#         'energy (kw 15min)',
#         'avg rhm'
#     ],
#     "multivariate (season)": [
#         'energy (kw 15min)',
#         'season idx'
#     ]
}

# Input Report Simulation
IRS = []

for key in _.keys():
    for jump in [3,4,6,8,12,24]:
        IRS.append(
            LEARN_INFO(name="{} / new matching {}".format(key,jump), 
                       columns=_[key], 
                       is_contain_cluster_label=True,
                       matching_type="split",
                      jump=jump),
        )

# Training Model Array 
TMA = []

is_switch = False

for _ in IRS:
    cm = ClusterModel(name=_.name,
                   columns=_.columns,
                   is_contain_cluster_label=_.is_label,
                   is_switch=is_switch,
                   matching_type=_.matching,
                   jump=_.jump)
    
    cm.set_window()
    cm.set_model()
    print(cm)
    cm.training(epochs=50)
    
    cm.set_predict(is_reshape=True)
    cm.set_predict(is_reshape=True, is_val_datas=True)
    
    TMA.append(cm)
    
test_evaluate_df = pd.DataFrame();
val_evaluate_df = pd.DataFrame();

for _ in TMA:
    test_evaluate_df = test_evaluate_df.append(_.statistic(), ignore_index=True)
    val_evaluate_df = val_evaluate_df.append(_.statistic(is_val_datas=True), ignore_index=True)
    
test_evaluate_df.index = [_.name for _ in TMA]
val_evaluate_df.index = [_.name for _ in TMA]

###### [Notice] (multivariate (weather) / new matching 24) set predict (validation) info start ###### 

0 / 91
50 / 91
91 / 91 complete.

###### [Notice] set predict info success ###### 



In [6]:
test_evaluate_df

cos        ecv       mae  mean dis  \
univariate / new matching 3   0.941212  71.679662  0.272847  1.495252   
univariate / new matching 4   0.943768  70.812382  0.276431  1.512685   
univariate / new matching 6   0.941088  72.058786  0.265161  1.473459   
univariate / new matching 8   0.943635  71.398986  0.269621  1.489586   
univariate / new matching 12  0.942119  71.276933  0.269745  1.492652   
univariate / new matching 24  0.943051  70.662567  0.271847  1.503669   

                              mean sim       mse          tss         wss  
univariate / new matching 3   0.931552  0.114899  1456.910039  412.601850  
univariate / new matching 4   0.933367  0.118418  1456.910039  425.237335  
univariate / new matching 6   0.930772  0.113361  1456.910039  407.078359  
univariate / new matching 8   0.932827  0.116038  1456.910039  416.691040  
univariate / new matching 12  0.931249  0.116533  1456.910039  418.469241  
univariate / new matching 24  0.931989  0.119025  1456.910039  427.420005

In [7]:
val_evaluate_df

cos        ecv       mae  mean dis  \
univariate / new matching 3   0.930975  64.203881  0.323585  1.742460   
univariate / new matching 4   0.933169  63.999924  0.323424  1.745392   
univariate / new matching 6   0.931975  65.514079  0.312060  1.703014   
univariate / new matching 8   0.933503  65.176657  0.314214  1.711549   
univariate / new matching 12  0.932474  64.997538  0.314726  1.715672   
univariate / new matching 24  0.933371  64.866758  0.314488  1.716662   

                              mean sim       mse         tss         wss  
univariate / new matching 3   0.911777  0.155940  832.494756  298.000817  
univariate / new matching 4   0.913213  0.156828  832.494756  299.698744  
univariate / new matching 6   0.911682  0.150232  832.494756  287.093488  
univariate / new matching 8   0.912968  0.151702  832.494756  289.902505  
univariate / new matching 12  0.911702  0.152482  832.494756  291.393663  
univariate / new matching 24  0.912345  0.153052  832.494756  292.482398